// <auto-generated />
namespace LTQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class crate_table_employee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crate_table_employee));
        
        string IMigrationMetadata.Id
        {
            get { return "202109140630108_crate_table_employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
